# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161207_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicao',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
